--dataset cifar100 \
--batch_size 128 \
--model_name VGG9 \
--model_path CMI/checkpoints/pretrained/main/cifar100_lda0.9_iba_avg3.pth.tar \
--save_dir run/cifar100_iba \
--framework alignins \
--pattern_type plus \
--attack iba \
