--dataset tinyimagenet \
--batch_size 64 \
--model_name resnet101_imagenet \
--model_path AlignIns/src/checkpoints/tinyimagenet_badnet_avg_resnet101.pth.tar \
--save_dir run/cmi_resnet101 \
--framework alignins \
--pattern_type plus \
--attack badnet \
